/**
 * GitHub client.
 *
 * This module holds every irreversible action SENTINEL can take, so the rules
 * are strict and enforced here rather than trusted to the prompt:
 *
 *  - A write refuses outright when `allowRemoteWrites` is false. The approval
 *    gate is the *second* line of defence, not the only one.
 *  - Branch names are generated by us, never by the model, and validated.
 *  - The token is never returned, logged, or echoed into a tool result.
 */
import { SentinelError, notConfigured } from "./errors.ts";
import { httpJson, httpRequest } from "./http.ts";

const API = "https://api.github.com";

export interface RepoRef {
  readonly owner: string;
  readonly repo: string;
}

const OWNER_RE = /^[A-Za-z0-9](?:[A-Za-z0-9-]{0,38})$/;
const REPO_RE = /^[A-Za-z0-9._-]{1,100}$/;

/** Parse and validate `owner/repo`, rejecting anything that could alter a path. */
export function parseRepo(input: string): RepoRef {
  const trimmed = input.trim().replace(/^https?:\/\/github\.com\//i, "").replace(/\.git$/, "");
  const parts = trimmed.split("/").filter((p) => p.length > 0);
  if (parts.length !== 2) {
    throw new SentinelError("invalid_input", `Expected "owner/repo", got "${input}".`);
  }
  const [owner, repo] = parts as [string, string];
  if (!OWNER_RE.test(owner)) {
    throw new SentinelError("invalid_input", `Invalid repository owner "${owner}".`);
  }
  if (!REPO_RE.test(repo) || repo === "." || repo === "..") {
    throw new SentinelError("invalid_input", `Invalid repository name "${repo}".`);
  }
  return { owner, repo };
}

/** Git refs have real syntax rules; violating them corrupts a repo. */
export function isValidBranchName(name: string): boolean {
  if (name.length === 0 || name.length > 255) return false;
  if (name.startsWith("/") || name.endsWith("/") || name.endsWith(".lock")) return false;
  if (name.includes("..") || name.includes("//") || name.includes("@{")) return false;
  // Control characters and ref-invalid punctuation. `no-control-regex` does not
  // fire on a character class, so no disable directive is needed here.
  if (/[\0-\x20~^:?*[\\\x7f]/.test(name)) return false;
  return true;
}

export class GitHubClient {
  readonly #token: string | null;
  readonly #allowWrites: boolean;

  constructor(token: string | null, allowWrites: boolean) {
    this.#token = token;
    this.#allowWrites = allowWrites;
  }

  get configured(): boolean {
    return this.#token !== null;
  }

  get writesAllowed(): boolean {
    return this.#allowWrites;
  }

  #headers(): Record<string, string> {
    if (this.#token === null) {
      throw notConfigured("GitHub access", "GITHUB_TOKEN");
    }
    return {
      accept: "application/vnd.github+json",
      authorization: `Bearer ${this.#token}`,
      "user-agent": "sentinel-strike-team",
      "x-github-api-version": "2022-11-28",
      "content-type": "application/json",
    };
  }

  /** Called by every mutating method before it does anything. */
  #assertWritable(action: string): void {
    if (!this.#allowWrites) {
      throw new SentinelError(
        "forbidden",
        `${action} is blocked: SENTINEL is running in read-only mode.`,
        "Set SENTINEL_ALLOW_REMOTE_WRITES=true to permit remote writes.",
      );
    }
  }

  // ------------------------------------------------------------- reads

  async getRepo(ref: RepoRef): Promise<{ defaultBranch: string; private: boolean }> {
    const data = await httpJson<{ default_branch?: string; private?: boolean }>(
      `${API}/repos/${ref.owner}/${ref.repo}`,
      { headers: this.#headers() },
    );
    return {
      defaultBranch: data.default_branch ?? "main",
      private: data.private ?? false,
    };
  }

  /** Fetch a file's decoded contents, or null when it does not exist. */
  async getFile(ref: RepoRef, path: string, branch?: string): Promise<string | null> {
    if (path.includes("..")) {
      throw new SentinelError("invalid_input", `Refusing to read path containing "..": ${path}`);
    }
    const query = branch === undefined ? "" : `?ref=${encodeURIComponent(branch)}`;
    const url = `${API}/repos/${ref.owner}/${ref.repo}/contents/${encodeURI(path)}${query}`;
    const result = await httpRequest(url, { headers: this.#headers() });
    if (result.status === 404) return null;
    if (!result.ok) {
      throw new SentinelError("upstream_failure", `GitHub returned ${result.status} for ${path}.`);
    }
    const body = JSON.parse(result.text) as { content?: string; encoding?: string };
    if (body.encoding !== "base64" || typeof body.content !== "string") {
      throw new SentinelError("upstream_failure", `Unexpected content encoding for ${path}.`);
    }
    return Buffer.from(body.content, "base64").toString("utf8");
  }

  async listOpenPullRequests(ref: RepoRef): Promise<{ number: number; title: string; head: string }[]> {
    const data = await httpJson<{ number: number; title: string; head: { ref: string } }[]>(
      `${API}/repos/${ref.owner}/${ref.repo}/pulls?state=open&per_page=100`,
      { headers: this.#headers() },
    );
    return data.map((pr) => ({ number: pr.number, title: pr.title, head: pr.head.ref }));
  }

  // ------------------------------------------------------------ writes

  async #getBranchSha(ref: RepoRef, branch: string): Promise<string> {
    const data = await httpJson<{ object?: { sha?: string } }>(
      `${API}/repos/${ref.owner}/${ref.repo}/git/ref/heads/${encodeURIComponent(branch)}`,
      { headers: this.#headers() },
    );
    const sha = data.object?.sha;
    if (typeof sha !== "string") {
      throw new SentinelError("not_found", `Could not resolve branch "${branch}".`);
    }
    return sha;
  }

  async createBranch(ref: RepoRef, branch: string, fromBranch: string): Promise<void> {
    this.#assertWritable("Creating a branch");
    if (!isValidBranchName(branch)) {
      throw new SentinelError("invalid_input", `Invalid branch name "${branch}".`);
    }
    const sha = await this.#getBranchSha(ref, fromBranch);
    const result = await httpRequest(`${API}/repos/${ref.owner}/${ref.repo}/git/refs`, {
      method: "POST",
      headers: this.#headers(),
      body: JSON.stringify({ ref: `refs/heads/${branch}`, sha }),
    });
    // 422 means it already exists, which is fine for a retried run.
    if (!result.ok && result.status !== 422) {
      throw new SentinelError(
        "upstream_failure",
        `Could not create branch "${branch}": HTTP ${result.status}.`,
      );
    }
  }

  async putFile(
    ref: RepoRef,
    path: string,
    content: string,
    message: string,
    branch: string,
  ): Promise<void> {
    this.#assertWritable("Committing a file");
    if (path.includes("..")) {
      throw new SentinelError("invalid_input", `Refusing to write path containing "..": ${path}`);
    }

    // A blob update needs the prior sha; omitting it on an existing file fails.
    let sha: string | undefined;
    const existing = await httpRequest(
      `${API}/repos/${ref.owner}/${ref.repo}/contents/${encodeURI(path)}?ref=${encodeURIComponent(branch)}`,
      { headers: this.#headers() },
    );
    if (existing.ok) {
      const body = JSON.parse(existing.text) as { sha?: string };
      sha = body.sha;
    }

    const result = await httpRequest(
      `${API}/repos/${ref.owner}/${ref.repo}/contents/${encodeURI(path)}`,
      {
        method: "PUT",
        headers: this.#headers(),
        body: JSON.stringify({
          message,
          content: Buffer.from(content, "utf8").toString("base64"),
          branch,
          ...(sha === undefined ? {} : { sha }),
        }),
      },
    );
    if (!result.ok) {
      throw new SentinelError(
        "upstream_failure",
        `Could not commit ${path}: HTTP ${result.status}.`,
      );
    }
  }

  async createPullRequest(
    ref: RepoRef,
    options: { title: string; body: string; head: string; base: string; draft?: boolean },
  ): Promise<{ number: number; url: string }> {
    this.#assertWritable("Opening a pull request");
    const data = await httpJson<{ number?: number; html_url?: string }>(
      `${API}/repos/${ref.owner}/${ref.repo}/pulls`,
      {
        method: "POST",
        headers: this.#headers(),
        body: JSON.stringify({
          title: options.title,
          body: options.body,
          head: options.head,
          base: options.base,
          draft: options.draft ?? false,
        }),
        retries: 0, // never silently retry a create - it would double-open
      },
    );
    if (typeof data.number !== "number" || typeof data.html_url !== "string") {
      throw new SentinelError("upstream_failure", "GitHub did not return a pull request.");
    }
    return { number: data.number, url: data.html_url };
  }

  async mergePullRequest(
    ref: RepoRef,
    number: number,
    method: "merge" | "squash" | "rebase" = "squash",
  ): Promise<{ merged: boolean; message: string }> {
    this.#assertWritable("Merging a pull request");
    const result = await httpRequest(
      `${API}/repos/${ref.owner}/${ref.repo}/pulls/${number}/merge`,
      {
        method: "PUT",
        headers: this.#headers(),
        body: JSON.stringify({ merge_method: method }),
        retries: 0,
      },
    );
    const body = JSON.parse(result.text || "{}") as { merged?: boolean; message?: string };
    return {
      merged: body.merged === true,
      message: body.message ?? (result.ok ? "Merged." : `HTTP ${result.status}`),
    };
  }
}

/** Deterministic, collision-resistant, and never model-authored. */
export function remediationBranchName(seed: string): string {
  const slug = seed
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40);
  const stamp = new Date().toISOString().slice(0, 10).replaceAll("-", "");
  const nonce = globalThis.crypto.randomUUID().slice(0, 6);
  return `sentinel/${stamp}-${slug.length > 0 ? slug : "remediation"}-${nonce}`;
}
